### PR TITLE
feat: add variable validation in org policy v2

### LINKED ISSUE #148: Add validation for policy_root in org_policy_v2 sub-module
### TL;DR

Add validation for policy_root in org_policy_v2 sub-module

### Terraform Resources

_No response_

### Detailed design

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by imrannayer**
fix #148

### CODE REVIEW

**Review by bharathkkb — APPROVED** [review]

**Comment by imrannayer** [comment]
@bharathkkb I dont have permission on this repo, can u plz merge it?

**Pull request merged**
